# Generated by Django 3.2.9 on 2021-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
