# Generated by Django 3.2.9 on 2021-11-25 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingdays',
            name='roles',
        ),
        migrations.AddField(
            model_name='workingdays',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='project.role'),
        ),
    ]
