# Generated by Django 3.2.9 on 2021-12-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_roles',
        ),
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='project.project'),
            preserve_default=False,
        ),
    ]
