# Generated by Django 3.2.9 on 2021-12-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211203_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
