# Generated by Django 3.2.9 on 2021-11-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211126_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public_shared',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
