# Generated by Django 3.2.9 on 2021-11-28 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20211129_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingdays',
            name='member',
        ),
        migrations.AddField(
            model_name='role',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
