# Generated by Django 3.2.9 on 2021-11-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20211129_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingdays',
            name='roles',
        ),
        migrations.AddField(
            model_name='workingdays',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='project.Role'),
        ),
    ]
