# Generated by Django 3.2.9 on 2021-11-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20211129_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
