# Generated by Django 3.2.9 on 2021-11-29 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20211129_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='project.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='project.project'),
        ),
        migrations.DeleteModel(
            name='WorkingDays',
        ),
    ]
