# Generated by Django 3.2.9 on 2021-11-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20211129_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='project',
        ),
    ]
