# Generated by Django 3.2.9 on 2021-11-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_role_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public',
            field=models.BooleanField(blank=True),
        ),
    ]
