# Generated by Django 3.2.9 on 2021-12-02 13:18

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(blank=True, max_length=250, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to=project.models.upload_attachment)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='project.AttachmentFile'),
        ),
    ]
