# Generated by Django 3.2.9 on 2021-12-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20211202_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentfile',
            old_name='file_name',
            new_name='attach_file',
        ),
    ]
